#######################################################################################
GET http://localhost:3000/api/user

###
GET http://localhost:3000/api/user/3

###
POST http://localhost:3000/api/user
Content-Type: application/json

{
    "username": "superadmin2",
    "password": "superadmin2",
    "first_name": "Super",
    "last_name": "Admin",
    "birth_date": "10-03-2001",
    "gender": "pria",
    "address": "H. Djiran",
    "RoleId": "2"
}

###
PUT http://localhost:3000/api/user/3
Content-Type: application/json

{
    "username": "admin123",
    "password": "admin123",
    "first_name": "admin",
    "last_name": "123",
    "birth_date": "10-03-2001",
    "gender": "pria",
    "address": "H. Djiran",
    "RoleId": "1"
}

###
DELETE http://localhost:3000/api/user/3

############################################################################################################
GET http://localhost:3000/api/attendance

###
POST http://localhost:3000/api/attendance
Authorization: Bearer eyJ1c2VybmFtZSI6InBlZ2F3YWkiLCJwYXNzd29yZCI6InBlZ2F3YWkifQ==

###
GET http://localhost:3000/api/attendance/eyJlbWFpbCI6InBlZ2F3YWkiLCJwYXNzd29yZCI6InBlZ2F3YWkifQ==

###############################################################################################################

GET http://localhost:3000/api/setting

###
GET http://localhost:3000/api/setting/balitbang

###
PUT http://localhost:3000/api/setting/balitbang
Content-Type: application/json

{
    "latitude": "123",
    "longitude": "123"
}

###############################################################################################################
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "username": "superadmin",
    "password": "superadmin"
}


###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "username": "pegawai",
    "password": "pegawai"
}

###############################################################################################################
GET http://localhost:3000/api/auth/eyJlbWFpbCI6InBlZ2F3YWkiLCJwYXNzd29yZCI6InBlZ2F3YWkifQ==

###
POST http://localhost:3000/api/upload

###
DELETE http://localhost:3000/api/cancel-upload

###
GET http://localhost:3000/api/reset